parameters:
  aw.rest_problem.listener.class: Alterway\Bundle\RestProblemBundle\EventListener\ProblemListener
  aw.rest_exception.listener.class: Alterway\Bundle\RestProblemBundle\EventListener\ExceptionListener

services:
  aw.rest_problem.listener:
    class: %aw.rest_problem.listener.class%
    arguments: [@annotation_reader]
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  aw.rest_exception.listener:
    class: %aw.rest_exception.listener.class%
    arguments: [%kernel.debug%]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
